---
title: "Homework 2"
author:
  - Makayla Whitney
  - Joe Swinehart
  - Janette Avelar
  - David Fainstein
date: "2/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(countrycode)
library(plotrix)
```

```{r data setup}

transit_cost <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-05/transit_cost.csv')

here::here("data")
crime <- read_csv(here("data","crime.csv"))
```

```{r transit plot}
# Pare down dataset
t_cost <- transit_cost %>% 
  select(country, real_cost)

# Load data to join for country names
country_codes <- countrycode::codelist %>% 
  select(country_name = country.name.en, country = ecb)

# Join dataset with country names
t_cost <- left_join(t_cost, country_codes, by = "country")

# Convert $real_cost to numeric
t_cost$real_cost <- as.numeric(t_cost$real_cost)

# Tidy + add mean + add standard error
cost_data <- t_cost %>% 
  group_by(country) %>% 
  mutate(cost = sum(real_cost),
         mean = mean(real_cost),
         se = sd(real_cost)/sqrt(n())) %>% 
  ungroup() %>% 
  select(-c(1, 2)) %>% 
  unique()

# Attempt mapping
ggplot(cost_data, aes(cost, country_name)) +
  geom_errorbar(aes(ymin = mean + qnorm(0.025)*se, 
                    ymax = mean + qnorm(0.975)*se))

```

```{r display uncertainity}


```

```{r crime plot}

#David can take this one on!

model_data <- crime %>% 
  mutate(neighborhood_id = relevel(factor(neighborhood_id), ref = "barnum"))

m <- glm(is_crime ~ neighborhood_id, 
         data = model_data,
         family = "binomial")

tidied <- broom::tidy(m)

ppoints(20)


```

```{r crime table}


```